name: Sanity checks
on: [push]

jobs:
  linters:
    runs-on: ubuntu-latest
    name: Lint Files
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Lint Files
        run: pre-commit run --all-files

